# Generated by Django 2.2.3 on 2019-08-06 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_post_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='images',
            field=models.ImageField(default='placeholder.jpg', upload_to='img'),
        ),
    ]
